apiVersion: v1
kind: ConfigMap
metadata:
  name: sdls-config
  namespace: sdls
data:
  MONGO_DB:              "distributed_logging"
  LOG_LEVEL:             "INFO"
  FLASK_DEBUG:           "0"
  FLASK_ENV:             "production"
  ORDER_SERVICE_URL:        "http://order-service:5001"
  PAYMENT_SERVICE_URL:      "http://payment-service:5002"
  INVENTORY_SERVICE_URL:    "http://inventory-service:5003"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5004"
  LOGGING_SERVICE_URL:      "http://logging-service:5005"
  API_GATEWAY_URL:          "http://api-gateway:5000"
  JWT_ALGORITHM:            "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "60"
